import { SectionName, Section, Stripe, StripeLevel } from "../index";

const S1_1: Section = {
  index: 0,
  stripe: StripeLevel.S1,
  section: SectionName.S1_1,
  nameEN: "Closed Guard From Bottom",
  nameHEB: "גארד סגור מלמטה",
  playlist: [
    {
      id: 0,
      stripe: StripeLevel.S1,
      section: SectionName.S1_1,
      url: "BmQyi1xy91E",
      titleHEB: "שמירה על פוזיציה",
      titleEN: "Keeping The Position",
      descriptionHEB:
        "הוא מנסה לפתוח את הגארד על הברכיים בתפיסת הברך ודחיפתה,הוא מכניס את המרפקים מתחת לברך",
      descriptionEN:
        "Opponent tries to open the guard on the knees by pushing the knee, inserting his elbows inside the knee.",
    },
    {
      id: 1,
      stripe: StripeLevel.S1,
      section: SectionName.S1_1,
      url: "CAxTyyk6hDE",
      titleHEB: "משולש",
      titleEN: "Triangle",
      descriptionHEB: "כשהוא מכניס יד בין הרגליים שלי",
      descriptionEN: "Opponent inserts his arm between your legs",
    },
    {
      id: 2,
      stripe: StripeLevel.S1,
      section: SectionName.S1_1,
      url: "tqYDMLHvtPc",
      titleHEB: "ג'וג'י גטאמה",
      titleEN: "Juji Gatame (Armbar)",
      descriptionHEB: "כשהוא מנסה לעשות לי חניקת איקס",
      descriptionEN: "Opponent tries to perform an X-Choke",
    },
    {
      id: 3,
      stripe: StripeLevel.S1,
      section: SectionName.S1_1,
      url: "TG1WRAT4TJg",
      titleHEB: "חניקת איקס",
      titleEN: "X-Choke",
      descriptionHEB: "כשהידיים שלו על הריצפה והוא קרוב אלי",
      descriptionEN:
        "Opponent's hands are on the ground and he is at a close distance",
    },
    {
      id: 4,
      stripe: StripeLevel.S1,
      section: SectionName.S1_1,
      url: "fFFUj6yjlYA",
      titleHEB: "קימורה",
      titleEN: "Kimura",
      descriptionHEB: "כשהידיים שלו על הריצפה והוא גבוהה",
      descriptionEN: "Opponent's hands are on the ground and he is upright",
    },
    {
      id: 5,
      stripe: StripeLevel.S1,
      section: SectionName.S1_1,
      url: "KcYOFmZE_Yo",
      titleHEB: "סויפ קימורה",
      titleEN: "Kimura Sweep",
      descriptionHEB:
        "כששתי הידיים שלו על החגורה  (כשהוא לא מונע ממני להתרומם)",
      descriptionEN: "Opponent's hands are on my belt",
    },
    {
      id: 6,
      stripe: StripeLevel.S1,
      section: SectionName.S1_1,
      url: "3ACPZTeyUE0",
      titleHEB: "הומופלטה",
      titleEN: "Omaplata",
      descriptionHEB: "כשהיריב מחבק אותי",
      descriptionEN: "Opponent is hugging me",
    },
    {
      id: 7,
      stripe: StripeLevel.S1,
      section: SectionName.S1_1,
      url: "7oTn3JvWxEU",
      titleHEB: "תפיסת גב",
      titleEN: "Back Take",
      descriptionHEB: "כששתי הידיים שלו בצד אחד שלי",
      descriptionEN: "Both of the opponents hands are on one side",
    },
    {
      id: 8,
      stripe: StripeLevel.S1,
      section: SectionName.S1_1,
      url: "REfXZhSNA4o",
      titleHEB: "פלאוור סויפ",
      titleEN: "Flower Sweep",
      descriptionHEB: "כשהיריב קם על רגל בלי לתפוס שרוול",
      descriptionEN: "Opponent stands up without controlling the sleeve",
    },
    {
      id: 9,
      stripe: StripeLevel.S1,
      section: SectionName.S1_1,
      url: "7BvUELlxgmU",
      titleHEB: "סויפ מספריים",
      titleEN: "Scissor Sweep",
      descriptionHEB: "כשהיריב קם על רגל בלי לתפוס שרוול",
      descriptionEN: "Opponent stands up without controlling the sleeve",
    },
  ],
};

const S1_2: Section = {
  index: 1,
  stripe: StripeLevel.S1,
  section: SectionName.S1_2,
  nameEN: "Closed Guard from Top",
  nameHEB: "גארד סגור מלמעלה",
  playlist: [
    {
      id: 0,
      stripe: StripeLevel.S1,
      section: SectionName.S1_2,
      url: "iTRlMbkw8FU",
      titleHEB: "פתיחה על הברכיים",
      titleEN: "Opening on knees",
      descriptionHEB: "",
      descriptionEN: "",
    },
    {
      id: 1,
      stripe: StripeLevel.S2,
      section: SectionName.S1_2,
      url: "KiJpB3fQYDE",
      titleHEB: "פתיחה בעמידה",
      titleEN: "Opening in standing position",
      descriptionHEB: "",
      descriptionEN: "",
    },
  ],
};

const S1_3: Section = {
  index: 2,
  stripe: StripeLevel.S1,
  section: SectionName.S1_3,
  nameEN: "Half Guard from Bottom",
  nameHEB: "חצי גארד מלמטה",
  playlist: [
    {
      id: 0,
      stripe: StripeLevel.S1,
      section: SectionName.S1_3,
      url: "OHSosDrQlbA",
      titleHEB: "שמירה על פוזיציה ",
      titleEN: "Retaining the Position",
      descriptionHEB: "הוא מנסה להגיע לקרוספייס, הוא דוחף/פותח את הברך שלי",
      descriptionEN: "",
    },
    {
      id: 1,
      stripe: StripeLevel.S1,
      section: SectionName.S1_3,
      url: "KeH2_KmRWXQ",
      titleHEB: "תפיסת גב",
      titleEN: "Back Take",
      descriptionHEB: "",
      descriptionEN: "",
    },
    {
      id: 2,
      stripe: StripeLevel.S1,
      section: SectionName.S1_3,
      url: "7lFzMXT9iV4",
      titleHEB: "הכנסה לגארד ",
      titleEN: "Entering Guard",
      descriptionHEB: "",
      descriptionEN: "",
    },
    {
      id: 3,
      stripe: StripeLevel.S1,
      section: SectionName.S1_3,
      url: "gS2FUwgMV2g",
      titleHEB: "קימה לטייקדאון ",
      titleEN: "Takedown",
      descriptionHEB: "",
      descriptionEN: "",
    },
  ],
};

const S1_4: Section = {
  index: 3,
  stripe: StripeLevel.S1,
  section: SectionName.S1_4,
  nameEN: "Half Guard from Top",
  nameHEB: "חצי גארד מלמעלה",
  playlist: [
    {
      id: 0,
      stripe: StripeLevel.S1,
      section: SectionName.S1_4,
      url: "JhClPUUEkKQ",
      titleHEB: "שמירה על הפוזיציה",
      titleEN: "Retaining The Position",
      descriptionHEB: "כשהוא שם אנדרהוק",
      descriptionEN: "Opponent places an underhook",
    },
    {
      id: 1,
      stripe: StripeLevel.S1,
      section: SectionName.S1_4,
      url: "1Acn7wVUC4c",
      titleHEB: "גיליוטינה",
      titleEN: "Guillutine",
      descriptionHEB: "",
      descriptionEN: "",
    },
    {
      id: 2,
      stripe: StripeLevel.S1,
      section: SectionName.S1_4,
      url: "lhWUiyM16L0",
      titleHEB: "ני סלייד",
      titleEN: "Knee Slide",
      descriptionHEB: "",
      descriptionEN: "",
    },
    {
      id: 3,
      stripe: StripeLevel.S1,
      section: SectionName.S1_4,
      url: "mkS3iHVwDJs",
      titleHEB: "מעבר למאונט",
      titleEN: "Moving to Mount",
      descriptionHEB: "",
      descriptionEN: "",
    },
  ],
};

const S1_5: Section = {
  index: 4,
  stripe: StripeLevel.S1,
  section: SectionName.S1_5,
  nameEN: "Throws",
  nameHEB: "הטלות",
  playlist: [
    {
      id: 0,
      stripe: StripeLevel.S1,
      section: SectionName.S1_5,
      url: "Rc785Mw8z2A",
      titleHEB: "דאבל לג",
      titleEN: "Double Leg",
      descriptionHEB: "",
      descriptionEN: "",
    },
  ],
};

const S2_1: Section = {
  index: 0,
  stripe: StripeLevel.S2,
  section: SectionName.S2_1,
  nameEN: "Side Control from Top",
  nameHEB: "סייד מלמעלה",
  playlist: [
    {
      id: 1,
      stripe: StripeLevel.S2,
      section: SectionName.S2_1,
      url: "QeQ7Cp9Yl8M",
      titleHEB: "שמירה על הפוזיציה",
      titleEN: "Retaining the Position",
      descriptionHEB:
        "הוא מכניס אנדרהוק וזוחל, הוא דוחף לי את המותן עם היד שקרובה לראש",
      descriptionEN:
        "Opponent inserts an underhook, opponent pushes my waist with arm close to head",
    },
    {
      id: 2,
      stripe: StripeLevel.S2,
      section: SectionName.S2_1,
      url: "XL4Vj-11AKc",
      titleHEB: "משולש ידיים",
      titleEN: "Arm Triangle",
      descriptionHEB: "כשאני בקרוס פייס והוא מיישר את היד עם פריים",
      descriptionEN:
        "Starting in crossface, and opponent straightens arm with a frame",
    },
    {
      id: 3,
      stripe: StripeLevel.S2,
      section: SectionName.S2_1,
      url: "Fd2lVPylYHU",
      titleHEB: "אמריקנה",
      titleEN: "Americana",
      descriptionHEB: "כשהיד שלו חשופה ופונה כלפיי הראש",
      descriptionEN: "Opponents arm is free and bent towards his head",
    },
    {
      id: 4,
      stripe: StripeLevel.S2,
      section: SectionName.S2_1,
      url: "Icz_qbcNXUk",
      titleHEB: "קימורה",
      titleEN: "Kimura",
      descriptionHEB: "כשהיד שלו חשופה ופונה כלפיי הרגליים",
      descriptionEN: "Opponents arm is free and bent towards his feet",
    },
    {
      id: 5,
      stripe: StripeLevel.S2,
      section: SectionName.S2_1,
      url: "ZDybi6XyOc4",
      titleHEB: "בריח יד ישרה",
      titleEN: "Straight arm break",
      descriptionHEB: "כשהיד שלו חשופה והמרפק נעול",
      descriptionEN: "Opponents arm is free, with his elbow locked",
    },
    {
      id: 6,
      stripe: StripeLevel.S2,
      section: SectionName.S2_1,
      url: "1QpwcwX9BJ4",
      titleHEB: "קאט דה צ'יז",
      titleEN: "Cut The Cheese",
      descriptionHEB: "כשהיד שקרובה לרגליים שלי לא במסגרת",
      descriptionEN: "Opponents arm which is close to my legs are not in frame",
    },
    {
      id: 7,
      stripe: StripeLevel.S2,
      section: SectionName.S2_1,
      url: "s9et3vtP4ro",
      titleHEB: "עלייה בסיסית א",
      titleEN: "Up to mount 1",
      descriptionHEB: "כשהרגליים שלו כפופות",
      descriptionEN: "Opponents legs are open",
    },
    {
      id: 8,
      stripe: StripeLevel.S2,
      section: SectionName.S2_1,
      url: "v1aFhxCVrlU",
      titleHEB: "עלייה בסיסית ב",
      titleEN: "Up to mount 2",
      descriptionHEB: "כשהרגל הקרובה אלי מורמת",
      descriptionEN: "Opponents leg is raised",
    },
    {
      id: 9,
      stripe: StripeLevel.S2,
      section: SectionName.S2_1,
      url: "CUFK2MDs0Lo",
      titleHEB: "עלייה עם ברך על הבטן",
      titleEN: "Knee On Belly",
      descriptionHEB: "כשהרגל הקרובה אלי מורמת",
      descriptionEN: "Opponents leg is raised",
    },
  ],
};

const S2_2: Section = {
  index: 1,
  stripe: StripeLevel.S2,
  section: SectionName.S2_2,
  nameEN: "Side Control from Bottom",
  nameHEB: "סייד מלמטה",
  playlist: [
    {
      id: 0,
      stripe: StripeLevel.S2,
      section: SectionName.S2_2,
      url: "DJ4KnMFMTyQ",
      titleHEB: "הכנסה לגארד עם קרוספייס",
      titleEN: "Entering guard from crossface",
      descriptionHEB: "נכנס לא גארד כיש לו כרוספייס",
      descriptionEN: "Entering guard when opponent has crossface",
    },
    {
      id: 1,
      stripe: StripeLevel.S2,
      section: SectionName.S2_2,
      url: "FbK70eW9two",
      titleHEB: "הכנסה לגארד בלי קרוספייס",
      titleEN: "Entering guard without crossface",
      descriptionHEB: "נכנס לא גארד כאין לו כרוספייס",
      descriptionEN: "Entering guard when opponent is without crossface",
    },
    {
      id: 2,
      stripe: StripeLevel.S2,
      section: SectionName.S2_2,
      url: "-cTS--RLfcI",
      titleHEB: "הפיכה עם גשר",
      titleEN: "Sweep with bridge",
      descriptionHEB: "כשהוא מנסה לעלות למאונט בלי קרוספייס",
      descriptionEN: "Opponent attempts to mount without crossface",
    },
    {
      id: 3,
      stripe: StripeLevel.S2,
      section: SectionName.S2_2,
      url: "rfdr9aNgiQM",
      titleHEB: "הסתובבות על הברכיים וסינגל לג",
      titleEN: "Knee turn with single leg",
      descriptionHEB: "כשהוא נשאר על הברכיים",
      descriptionEN: "Opponent stays on their knees",
    },
    {
      id: 4,
      stripe: StripeLevel.S2,
      section: SectionName.S2_2,
      url: "HpyIUBU68Fk",
      titleHEB: "הסתובבות על הברכיים והפיכה ",
      titleEN: "Knee turn with sweep",
      descriptionHEB: "הוא מחבק אותי עם שתי ידיים",
      descriptionEN: "Opponent holds me with two arms",
    },
    {
      id: 5,
      stripe: StripeLevel.S2,
      section: SectionName.S2_2,
      url: "WxCMN9a7YBE",
      titleHEB: "הסתובבות על הברכיים ויציאה לטרטל",
      titleEN: "Knee turn with escape to turtle",
      descriptionHEB: "הוא עושה ספרול",
      descriptionEN: "Opponent attempts to sprawl",
    },
  ],
};

const S2_3: Section = {
  index: 2,
  stripe: StripeLevel.S2,
  section: SectionName.S2_3,
  nameEN: "Kesa-Gatame",
  nameHEB: "סייד מלמטה",
  playlist: [
    {
      id: 0,
      stripe: StripeLevel.S2,
      section: SectionName.S2_3,
      url: "CHjcsgZD3P8",
      titleHEB: "שתי יציאות עם מסגרת והוק",
      titleEN: "Hook and frame escapes",
      descriptionHEB: "יצאיות עם הוק ומסגרת",
      descriptionEN: "Two escapes with frame and hook",
    },
    {
      id: 1,
      stripe: StripeLevel.S2,
      section: SectionName.S2_3,
      url: "1KXEDtPjSOw",
      titleHEB: "יציאה בלי הוק",
      titleEN: "Escape without hook",
      descriptionHEB: "יציאה בלי הוק",
      descriptionEN: "Escape without hook",
    },
    {
      id: 2,
      stripe: StripeLevel.S2,
      section: SectionName.S2_3,
      url: "DJ4KnMFMTyQ",
      titleHEB: "יציאה בלי מסגרת ובלי הוק",
      titleEN: "Escape without frame or hook",
      descriptionHEB: "יציאה בלי מסגרת ובלי הוק",
      descriptionEN: "Escape without frame or hook",
    },
  ],
};

const S2_4: Section = {
  index: 3,
  stripe: StripeLevel.S2,
  section: SectionName.S2_4,
  nameEN: "Throws",
  nameHEB: "הטלות",
  playlist: [
    {
      id: 0,
      stripe: StripeLevel.S2,
      section: SectionName.S2_4,
      url: "FhYrwN2USYE",
      titleHEB: "הטלת מותן 1",
      titleEN: "Hip throw 1",
      descriptionHEB: "הטלת מותן 1",
      descriptionEN: "Hip throw 1",
    },
    {
      id: 1,
      stripe: StripeLevel.S2,
      section: SectionName.S2_4,
      url: "zQDTpgSUSUw",
      titleHEB: "הטלת מותן 2",
      titleEN: "Hip throw 2",
      descriptionHEB: "הטלת מותן 2",
      descriptionEN: "Hip throw 2",
    },
    {
      id: 2,
      stripe: StripeLevel.S2,
      section: SectionName.S2_4,
      url: "WdPDGO-RrFA",
      titleHEB: "ספרול כנגד דאבל לג",
      titleEN: "Sprawl resisting double leg",
      descriptionHEB: "ספרול כנגד דאבל לג",
      descriptionEN: "Sprawl resisting double leg",
    },
  ],
};

const S3_1: Section = {
  index: 0,
  stripe: StripeLevel.S3,
  section: SectionName.S3_1,
  nameEN: "Open Guard From Bottom (sitting)",
  nameHEB: "גארד פתוח מלמטה (בשכיבה)",
  playlist: [
    {
      id: 0,
      stripe: StripeLevel.S3,
      section: SectionName.S3_1,
      url: "pOGw4SlOWdc",
      titleHEB: "שמירה על הגארד",
      titleEN: "Retaining the Guard",
      descriptionHEB:
        "היריב הולך מסביבי, הרמה של עקב אחד וצעד מקביל,זריקה של שני העקבים וצעד באלכסון,אותו דבר עם צעד מעל הראש, אותו דבר עם צעד מעל הגוף, תפיסת ברך וזריקה לצד הרחוק",
      descriptionEN:
        "**The opponent walks around me, lifting one heel and a parallel step, throwing both heels and stepping diagonally, the same with a step above the head, the same with a step above the body, grabbing a knee and throwing to the far side",
    },
    {
      id: 1,
      stripe: StripeLevel.S3,
      section: SectionName.S3_1,
      url: "bj6AEWC7Xho",
      titleHEB: "סויפ בת ים",
      titleEN: "Mermaid Sweep",
      descriptionHEB: "כשהוא קרוב עם הכפות רגליים",
      descriptionEN: "**When he is close with his feet",
    },
    {
      id: 2,
      stripe: StripeLevel.S3,
      section: SectionName.S3_1,
      url: "1AvXe7MyaEc",
      titleHEB: "סויפ סופרמן",
      titleEN: "Superman Sweep",
      descriptionHEB: "כשהוא נשען עליי",
      descriptionEN: "**When he leans on me",
    },
    {
      id: 3,
      stripe: StripeLevel.S3,
      section: SectionName.S3_1,
      url: "E0oGOmghETI",
      titleHEB: "סויפ טריפוד",
      titleEN: "Tripod Sweep",
      descriptionHEB: "כשהוא עומד עם רגל אחת קרוב אליי",
      descriptionEN: "**When he stands with one leg close to me",
    },
  ],
};

const S3_2: Section = {
  index: 1,
  stripe: StripeLevel.S3,
  section: SectionName.S3_2,
  nameEN: "Open Guard From Top (Opponent in sitting position)",
  nameHEB: "גארד פתוח מלמעלה  (היריב בשכיבה)",
  playlist: [
    {
      id: 0,
      stripe: StripeLevel.S3,
      section: SectionName.S3_2,
      url: "pOGw4SlOWdc",
      titleHEB: "מעבר לברך על הבטן",
      titleEN: "**Positioning to Knee On Belly",
      descriptionHEB: "כשהיריב עם רגליים רפויות",
      descriptionEN: "**When the opponent is loose-legged",
    },
    {
      id: 1,
      stripe: StripeLevel.S3,
      section: SectionName.S3_2,
      url: "ngReEL2k5Jo",
      titleHEB: "מעבר למאונט",
      titleEN: "**Positioning to Mount",
      descriptionHEB: "כשהיריב דוחף אותי",
      descriptionEN: "**When the opponent pushes me",
    },
    {
      id: 2,
      stripe: StripeLevel.S3,
      section: SectionName.S3_2,
      url: "KnazFEbhII0",
      titleHEB: "טוריאדה",
      titleEN: "Toriada",
      descriptionHEB: "שהוא מצמיד ברכיים לחזה כמו שצריך",
      descriptionEN: "**that he puts his knees to his chest properly",
    },
    {
      id: 3,
      stripe: StripeLevel.S3,
      section: SectionName.S3_2,
      url: "0",
      titleHEB: "ניסלייד",
      titleEN: "Kneeslide",
      descriptionHEB: "-",
      descriptionEN: "-",
    },
  ],
};


export const W1_PLAYLIST: Stripe = {
  stripe: StripeLevel.S1,
  playlist: [S1_1, S1_2, S1_3, S1_4, S1_5 ]
}
export const W2_PLAYLIST: Stripe = {
  stripe: StripeLevel.S2,
  playlist: [S2_1, S2_2, S2_3, S2_4 ]
}
export const W3_PLAYLIST: Stripe = {
  stripe: StripeLevel.S3,
  playlist: [S3_1, S3_2]
}
